moved to correct location

diff --git a/JavaArjuna/v0.1.0/configure b/JavaArjuna/v0.1.0/configure
--- a/JavaArjuna/v0.1.0/configure
+++ b/JavaArjuna/v0.1.0/configure
@@ -1,14 +1,14 @@
 #!/bin/sh
 
 #
-# Copyright (C) 1995, 1996, 1997, 1998, 1999,
+# Copyright (C) 1995, 1996
 # 
 # Department of Computing Science,
 # University of Newcastle upon Tyne,
 # Newcastle upon Tyne,
 # UK.
 # 
-# $Id: configure,v 1.19.2.2 1999/02/05 09:52:37 nmcl Exp $
+# $Id: configure,v 1.1 1997/07/31 09:13:01 nmcl Exp $
 #
 
 if test "$#" = "0"
@@ -46,7 +46,7 @@ if test "$CONFIGFILE" != ""
 then
 	if test -f $CONFIGFILE
 	then
-		if test "`head -11 $CONFIGFILE | tail -1`" != "# JavaArjuna configure file"
+		if test "`head -11 $CONFIGFILE | tail -1`" != "# JavaStubGenerator configure file"
 		then
 			echo $0": configuration file \""$CONFIGFILE"\" is invalid/corrupt"
 			exit 1
@@ -67,23 +67,66 @@ else
 	POST_ECHO=""
 fi
 
-ARJUNA_VERSION="0.1.0"
-
-echo "+------------------------------+"
-echo "| JavaArjuna version "$ARJUNA_VERSION" |"
-echo "+------------------------------+"
+echo "+-----------------------------------+"
+echo "|  JavaStubGenerator version 1.0.0  |"
+echo "+-----------------------------------+"
 
 if test "$CONFIGFILE" = ""
 then
 	TOPDIR=`pwd`
-	INSTALLTOPDIR=/usr/local/JavaArjuna$ARJUNA_VERSION
+	INSTALLTOPDIR=/usr/local/JavaStubGenerator1.0.0
+	GANDIVATOPDIR=/home/nmcl/ArjunaII/Gandiva
+	JAVAHARNESSTOPDIR=/home/nmcl/ArjunaII/JavaHarness
 
 	echo
-	echo $PRE_ECHO "Root of directory of JavaArjuna installation ["$INSTALLTOPDIR"] : " $POST_ECHO
+	echo $PRE_ECHO "Root of directory of JavaStubGenerator installation ["$INSTALLTOPDIR"] : " $POST_ECHO
 	read INPUT
 	if test "'x$INPUT'" != "'x'"
 	then
 		INSTALLTOPDIR=$INPUT
+	fi
+
+	echo
+	echo $PRE_ECHO "Root of directory of JavaHarness ["$JAVAHARNESSTOPDIR"] : " $POST_ECHO
+	read INPUT
+	if test "'x$INPUT'" != "'x'"
+	then
+		JAVAHARNESSTOPDIR=$INPUT
+	fi
+
+	echo
+	echo $PRE_ECHO "Root of directory of Gandiva ["$GANDIVATOPDIR"] : " $POST_ECHO
+	read INPUT
+	if test "'x$INPUT'" != "'x'"
+	then
+		GANDIVATOPDIR=$INPUT
+	fi
+
+	if test -x $GANDIVATOPDIR/config/Sys
+	then
+		SYS=`$GANDIVATOPDIR/config/Sys`
+	else
+		echo
+		echo "Error: "$GANDIVATOPDIR/config/Sys": was not found or would not run."
+		exit 1
+	fi
+
+	if test -x $GANDIVATOPDIR/config/Sys_Version
+	then
+		SYS_VERSION=`$GANDIVATOPDIR/config/Sys_Version`
+	else
+		echo
+		echo "Error: "$GANDIVATOPDIR/config/Sys_Version": was not found or would not run."
+		exit 1
+	fi
+
+	if test -x $GANDIVATOPDIR/config/C++
+	then
+		COMP=`$GANDIVATOPDIR/config/C++`
+	else
+		echo
+		echo "Error: "$GANDIVATOPDIR/config/C++": was not found or would not run."
+		exit 1
 	fi
 
 	case $SYS in
@@ -99,12 +142,12 @@ then
 		;;
 	esac
 
-	sed -e "s;INCLUDES;-Iconfig;" < MakefileBoot.tmpl > MakefileBoot
+	sed -e "s;INCLUDES;-Iconfig -I$JAVAHARNESSTOPDIR/config -I$GANDIVATOPDIR/config;" < MakefileBoot.tmpl > MakefileBoot
 
 	LOCAL_MAKEFLAGS=""
-	LOCAL_IMAKEFLAGS="-DVerboseMake=No -DBUILDDAEMONS -DINSTALLDAEMONS -DTopDir="$TOPDIR" -DInstallTopDir="$INSTALLTOPDIR
+	LOCAL_IMAKEFLAGS="-DVerboseMake=No -DTopDir="$TOPDIR" -DInstallTopDir="$INSTALLTOPDIR
 	LOCAL_MAKEDEPENDFLAGS=""
-	LOCAL_CPPFLAGS="-I\$(JAVAARJUNATOPDIR)/lib -DDEFAULT_OS_ROOT=\\\"\$(INSTALLTOPDIR)/ObjectStore\\\" -DDEFAULT_LS_ROOT=\\\"\$(INSTALLTOPDIR)/LockStore\\\""
+	LOCAL_CPPFLAGS="-I\$(JAVASTUBGENERATORTOPDIR)/lib"
 	LOCAL_CPPINCLUDES=""
 	LOCAL_CPLUSPLUSFLAGS=""
 	LOCAL_LDFLAGS=""
@@ -140,18 +183,31 @@ then
 	INPUT=""
 	while test "'x$INPUT'" != "'xy'" -a "'x$INPUT'" != "'xn'"
 	do
-		echo $PRE_ECHO "Build htdocs (y/n) : " $POST_ECHO
+		echo $PRE_ECHO "Build utility programs (y/n) : " $POST_ECHO
 		read INPUT
 	done
 	if test "'x$INPUT'" = "'xy'"
 	then	
-		LOCAL_IMAKEFLAGS="-DBUILDHTDOCS "$LOCAL_IMAKEFLAGS
+		INPUT=""
+		while test "'x$INPUT'" != "'xy'" -a "'x$INPUT'" != "'xn'"
+		do
+			echo $PRE_ECHO "Install utility programs (y/n) : " $POST_ECHO
+			read INPUT
+		done
+		if test "'x$INPUT'" = "'xy'"
+		then	
+			LOCAL_IMAKEFLAGS="-DBUILDUTILITIES -DINSTALLUTILITIES "$LOCAL_IMAKEFLAGS
+		else
+			LOCAL_IMAKEFLAGS="-DBUILDUTILITIES -UINSTALLUTILITIES "$LOCAL_IMAKEFLAGS
+		fi
+	else
+		LOCAL_IMAKEFLAGS="-UBUILDUTILITIES -UINSTALLUTILITIES "$LOCAL_IMAKEFLAGS
 	fi
 
 	MODULE_MAKEFLAGS=""
-	MODULE_IMAKEFLAGS="-I\$(JAVAARJUNATOPDIR)/config"
+	MODULE_IMAKEFLAGS="-I\$(JAVASTUBGENERATORTOPDIR)/config -DJavaStubGenProg=StubGenerator"
 	MODULE_MAKEDEPENDFLAGS=""
-	MODULE_CPPINCLUDES="-I\$(JAVAARJUNATOPDIR)/include"
+	MODULE_CPPINCLUDES="-I\$(JAVASTUBGENERATORTOPDIR)/include"
 	MODULE_CPLUSPLUSFLAGS=""
 	MODULE_LDFLAGS=""
 	MODULE_LDLIBRARIES=""
@@ -164,12 +220,12 @@ then
 	
 	if test $COMP = "CC3.0.1" -o $COMP = "SUNCC2.0.1" -o $COMP = "HPCC3.5"
 	then
-		MODULE_CPLUSPLUSFLAGS="-ptr\$(JAVAARJUNATOPDIR)/Templates.DB -I\$(JAVAARJUNATOPDIR)/include "$MODULE_CPLUSPLUSFLAGS
-		MODULE_LDFLAGS="-ptr\$(JAVAARJUNATOPDIR)/Templates.DB -I\$(JAVAARJUNATOPDIR)/include "$MODULE_LDFLAGS
+		MODULE_CPLUSPLUSFLAGS="-ptr\$(JAVASTUBGENERATORTOPDIR)/Templates.DB -I\$(JAVASTUBGENERATORTOPDIR)/include "$MODULE_CPLUSPLUSFLAGS
+		MODULE_LDFLAGS="-ptr\$(JAVASTUBGENERATORTOPDIR)/Templates.DB -I\$(JAVASTUBGENERATORTOPDIR)/include "$MODULE_LDFLAGS
 	elif test $COMP = "SUNCC3.0" -o $COMP = "SUNCC3.0.1"
 	then
-		MODULE_CPLUSPLUSFLAGS="-ptr\$(JAVAARJUNATOPDIR) -pti\$(JAVAARJUNATOPDIR)/include "$MODULE_CPLUSPLUSFLAGS
-		MODULE_LDFLAGS="-ptr\$(JAVAARJUNATOPDIR) -pti\$(JAVAARJUNATOPDIR)/include "$MODULE_LDFLAGS
+		MODULE_CPLUSPLUSFLAGS="-ptr\$(JAVASTUBGENERATORTOPDIR) -pti\$(JAVASTUBGENERATORTOPDIR)/include "$MODULE_CPLUSPLUSFLAGS
+		MODULE_LDFLAGS="-ptr\$(JAVASTUBGENERATORTOPDIR) -pti\$(JAVASTUBGENERATORTOPDIR)/include "$MODULE_LDFLAGS
 	fi
 
 else
@@ -311,7 +367,7 @@ fi
 (
 echo "#!/bin/sh"
 echo "#"
-echo "# Copyright (C) 1994, 1995, 1996, 1997,"
+echo "# Copyright (C) 1994, 1995, 1996"
 echo "#"
 echo "# Department of Computing Science,"
 echo "# University of Newcastle upon Tyne,"
@@ -319,9 +375,11 @@ echo "# Newcastle upon Tyne,"
 echo "# UK."
 echo "#"
 echo ""
-echo "# JavaArjuna configure file"
+echo "# JavaStubGenerator configure file"
 echo ""
 echo "INSTALLTOPDIR="$INSTALLTOPDIR
+echo "JAVAHARNESSTOPDIR="$JAVAHARNESSTOPDIR
+echo "GANDIVATOPDIR="$GANDIVATOPDIR
 echo ""
 echo "LOCAL_MAKEFLAGS='"$LOCAL_MAKEFLAGS"'"
 echo "LOCAL_IMAKEFLAGS='"$LOCAL_IMAKEFLAGS"'"
@@ -342,12 +400,12 @@ echo "MODULE_CPLUSPLUSFLAGS='"$MODULE_CPLUSPLUSFLAGS"'"
 echo "MODULE_LDFLAGS='"$MODULE_LDFLAGS"'"
 echo "MODULE_LDLIBRARIES='"$MODULE_LDLIBRARIES"'"
 echo "MODULE_LDLIBDEPENDS='"$MODULE_LDLIBDEPENDS"'"
-) > config/JavaArjuna.cf
-chmod a+rx config/JavaArjuna.cf
+) > config/JavaStubGenerator.cf
+chmod a+rx config/JavaStubGenerator.cf
 
 (
 echo "/*"
-echo " * Copyright (C) 1995, 1996, 1997,"
+echo " * Copyright (C) 1995, 1996"
 echo " *"
 echo " * Department of Computing Science,"
 echo " * University of Newcastle upon Tyne,"
@@ -398,12 +456,14 @@ then
 fi
 echo
 echo "#include \""$TOPDIR"/config/Module.def\""
+echo "#include \""$JAVAHARNESSTOPDIR"/config/Module.def\""
+echo "#include \""$GANDIVATOPDIR"/config/Module.def\""
 ) > config/Local.def
 chmod a+r config/Local.def
 
 (
 echo "/*"
-echo " * Copyright (C) 1995, 1996, 1997,"
+echo " * Copyright (C) 1995, 1996"
 echo " *"
 echo " * Department of Computing Science,"
 echo " * University of Newcastle upon Tyne,"
@@ -416,7 +476,7 @@ echo "/*"
 echo " *  Module.def (source)"
 echo " */"
 echo
-echo "JAVAARJUNATOPDIR="$TOPDIR
+echo "JAVASTUBGENERATORTOPDIR="$TOPDIR
 echo
 if test "'x$MODULE_MAKEFLAGS'" != "'x'"
 then
@@ -455,13 +515,13 @@ then
 	echo "AddToLdLibDepends("$MODULE_LDLIBDEPENDS")"
 fi
 echo
-echo "AddToCPPFlags(-DARJUNA_VERSION=\\\"$ARJUNA_VERSION\\\")"
+echo "#include \""$TOPDIR"/config/JavaStubGenerator.tmpl\""
 ) > config/Module.def
 chmod a+r config/Module.def
 
 (
 echo "/*"
-echo " * Copyright (C) 1995, 1996, 1997,"
+echo " * Copyright (C) 1995, 1996"
 echo " *"
 echo " * Department of Computing Science,"
 echo " * University of Newcastle upon Tyne,"
@@ -474,7 +534,7 @@ echo "/*"
 echo " *  Module.def (install)"
 echo " */"
 echo
-echo "JAVAARJUNATOPDIR="$INSTALLTOPDIR
+echo "JAVASTUBGENERATORTOPDIR="$INSTALLTOPDIR
 echo
 if test "'x$MODULE_MAKEFLAGS'" != "'x'"
 then
@@ -513,10 +573,6 @@ then
 	echo "AddToLdLibDepends("$MODULE_LDLIBDEPENDS")"
 fi
 echo
-echo "AddToCPPFlags(-DARJUNA_VERSION=\\\"$ARJUNA_VERSION\\\")"
+echo "#include \""$INSTALLTOPDIR"/config/JavaStubGenerator.tmpl\""
 ) > config/Module_install.def
 chmod a+r config/Module_install.def
-
-(
-echo "JavaArjuna version $ARJUNA_VERSION"
-) > config/Version.def
